homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  # 50.0761200N, 14.4600775E
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 252
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Prague
  # Customization file
  customize: !include customize.yaml

automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
frontend: !include frontend.yaml
group: !include groups.yaml
history_graph: !include history_graph.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
light: !include light.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml

#alarm_control_panel:
#  - platform: arlo

#android_ip_webcam:
#  - host: !secret android_ip_webcam
#    switches:
#      - night_vision
#      - torch
#      - video_recording

arlo:
  username: !secret arlo_email
  password: !secret arlo_password

camera:
  - platform: arlo
    ffmpeg_arguments: '-pred 1 -q:v 2'
  - platform: generic
    still_image_url: !secret meteogram_png_url
    name: Forecast

# Enables configuration UI
config:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

#customizer:
#  custom_ui: local

device_tracker:
  - platform: unifi_direct
    host: !secret unifi_ip
    username: !secret unifi_user
    password: !secret unifi_password
    consider_home: 60
    hide_if_away: yes

# Discover some devices automatically
discovery:

ffmpeg:

# Used for Google Calendar
google:
  client_id: !secret google_id
  client_secret: !secret google_secret

# Used for Google Home
#google_assistant:
#  project_id: someproject-2d0b8
#  client_id: !secret google_client_id
#  access_token: !secret google_access_token
#  agent_user_id: [a string to identify user]
#  api_key: [an API Key generated for the Google Actions project]
#  exposed_domains:
#    - switch
#    - light
#    - group
#    - climate
#    - script

# Enables support for tracking state changes over time
history:

http:
  api_password: !secret http_password
  base_url: !secret http_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

hue:
  bridges:
    - host: !secret philips_hue_bridge

ifttt:
  key: !secret ifttt

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
# map:

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

notify:
  - platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

remote:
  - platform: harmony
    name: TV
    activity: Watch TV

shopping_list:

sun:

timer:
  5minutes:
    duration: '00:05:00'

# Text to speech
tts:
  - platform: google

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

zwave:
  usb_path: /dev/ttyACM0
