- platform: flux
  lights:
    - light.angel
    - light.left
    - light.middle
    - light.right
    - light.bathroom_left
    - light.bathroom_right
    - light.kitchen_left_left
    - light.kitchen_left
    - light.kitchen_middle
    - light.kitchen_right
    - light.wc
    - light.office
  name: fluxer
  start_time: '7:30'
  stop_time: '22:00'
  start_colortemp: 6500
  sunset_colortemp: 3000
  stop_colortemp: 2200
  brightness: 1
  disable_brightness_adjust: True
  mode: mired
  transition: 30
  interval: 60

#- platform: rest
#  name: kitchen_motion_sensor
#  resource: !secret philips_hue_kitchen_sensor
#  body_on: '{"is_active": "true"}'
#  body_off: '{"is_active": "false"}'
#  is_on_template: '{{value_json.config.on}}'

#- platform: template
#  switches:
#    arlo_toggle:
#      friendly_name: Camera
#      value_template: "{{ 1==1 }}"
#      turn_on:
#        service: script.turn_on
#        data:
#          entity_id: script.arm_arlo
#      turn_off:
#        service: script.turn_off
#        data:
#          entity_id: script.disarm_arlo
